### ISSUE TITLE
highlight opens search window

### ISSUE THREAD

**Issue by SnowPrimate** [MLH-Fellowship/pod-3.1.3-team-2#8]
When highlighting a text, it should either immediately search for that or user should have the option to search it so we can implement the cards search.

**Comment by MsMore** [comment]
let's not jump onto anything that requires the highlight feature yet, I will work on it under issue #7. For now just implement the search from tiles.

Also the highlight feature will work this way:
1. user will highlight
2. it will get added to the list
3. later user can either keep it, delete it, search it on google from the tile, for which we need the features from issue #3 point no. 1 to 3
