### ISSUE TITLE
download file is the wrong way up

### ISSUE THREAD

**Issue by MsMore** [MLH-Fellowship/pod-3.1.3-team-2#9]
**bug:**
- the list after printing is inverted in time, latest notes being on top and oldest being on the bottom
**corrections needed:**
- the downloaded list.html should be according to timeline
-  the ones posted first should appear first.

**attention**
- do not change the list order in the popup itself, it is supposed to be that way; old notes should go at the bottom and new at the top.

** suggested code**
 on line 54 or somewhere around, we have
`list.innerHTML = listItem + list.innerHTML ;`
which puts new items in front of old ones, maybe  make a new variable and replace the order of it and make it print that or somewhere on that line.

**Comment by SnowPrimate** [comment]
Okay! nice, good idea.

**Comment by SnowPrimate** [comment]
Oh, now I understand. I though you would like to change the order. I feel like I'd prefer to have old nodes at the top and new at the bottom. It makes more sense to me. Like when you write down notes.
